name: firebase.google
on:mvn deploy -Dregistry=https://maven.pkg.github.com/androidb88 -Dtoken=GH_TOKEN
  push:
    branches: 
      - "master"
    paths:
      - "infra/build/**"
env:
  PROJECT_ID: ${{ c3714f38e6b0954c


}}

jobs:
  build-push-dev-tools:
    name: Build and push new CFT dev tools image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "286.0.0"
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Build
        run: |-
          cd infra/build && make build-image-developer-tools

      - name: Push
        run: |-
          gcloud auth configure-docker -q
          cd infra/build && make release-image-developer-tools
